### ISSUE TITLE
Document minimum aws version needed

### ISSUE THREAD

**Issue by lokst** [CircleCI-Public/aws-ecs-orb#100]
Document minimum aws version needed to support the `--include TAGS` option which the orb uses, and known machine executor images that do not have a new enough `aws` version pre-installed. This may help avoid issues like https://github.com/CircleCI-Public/aws-ecs-orb/issues/98.

Perhaps this could go into a "Common Problem Causes" section of the readme.

**Comment by devkapilbansal** [comment]
@lokst I want to look into this issue

**Comment by brivu** [comment]
The `--include` flag has been deprecated
