### ISSUE TITLE
Need to return the taskarn from run_task command

### ISSUE THREAD

**Issue by anveshagarwal** [CircleCI-Public/aws-ecs-orb#102]
## What would you like to be added
I am working on polling the task status that is run by `run_task`. Now i am not able to get the task arn. I tried to use aws-cli to get the task arn that is just initiated by the the `run_task`. But no command seems good for my usecase. So it will be much better if i can just get the taskarn from the `run_task` command in BASH_ENV.
## Why is this needed
It will make it much easy as straightforward to get the logs and poll the task which is intiated by run_task command.

**Comment by brivu** [comment]
Hey @anveshagarwal, 

If we were to save the `json` output from running the `run-task` command, would that help your use case?

Best, 
Brian
