### ISSUE TITLE
Deploying updates to Schedule Tasks

### ISSUE THREAD

**Issue by pbrisbin** [CircleCI-Public/aws-ecs-orb#104]
## What would you like to be added

I'd like to be able to use this Orb to deploy updates to Scheduled Tasks in addition to ECS Services.

I've built this as a [separate Orb](https://github.com/pbrisbin/aws-ecs-scheduled-tasks-orb/blob/master/src/jobs/deploy-scheduled-task-update.yml#L75-L95) for now. All the heavy lifting is provided by this Orb already; I just added an additional step to call `aws events put-targets`. I'm wondering if,

- You'd accept it as PR into this repository, and if so
- Is there anything I should know in adapting my linked to code for integrating here?

## Why is this needed

Scheduled Tasks are a very common way to deploy time-triggered actions on ECS that run your same Task Definitions as anything else. Supporting this directly in the official "aws-ecs" Orb makes more sense then something separate and un-official like what I have now.

**Comment by lokst** [comment]
@pbrisbin This sounds very useful! Let me get back to you soon on this 🙂

**Comment by oorestisime** [comment]
Any news here? i need this as well and would love if it was in the orb

**Comment by AlexandruTipter** [comment]
+

**Comment by pbrisbin** [comment]
:wave: I've moved from Circle to GitHub Actions generally and no longer use this Orb or my scheduled-task one, so I'm no longer invested in this issue. Just let me know if I can be helpful to anyone who wants to run with it themselves.

**Comment by AlexandruTipter** [comment]
It's fine, we cannot move and we still need this, so if there is still some light to this feature then i'm looking forward to it.

**Comment by brivu** [comment]
Hi @pbrisbin, @Retpit and @oorestisime, 

I'm working on the next major release of this orb and I'm looking into adding this. Can you give me some more details about your use case so I can understand how to add this into the orb and test it?

Best, 
Brian

**Comment by oorestisime** [comment]
Hey sorry for the delayed response. So basically on ECS we have a set of scheduled tasks. When the images change we need to update those tasks to use the new image.
This is not supported by the orb as far as i understand.
I ended up doing it with a python script. looks like

```
td_arn = os.environ.get("CCI_ORB_AWS_ECS_REGISTERED_TASK_DFN")
targets = event_client.list_targets_by_rule(Rule=rule)
targets["Targets"][0]["EcsParameters"]["TaskDefinitionArn"] = td_arn
## update the target
response = event_client.put_targets(Rule=rule, Targets=targets["Targets"])
```

Hope this helps. open to clarifications if needed

**Comment by brivu** [comment]
Hey @oorestisime, 

I resolved this with PR #168 and will cut a new major release in about a week. If you still have issues after the release, feel free to open a new issue. 

Thank you!
Brian

**Comment by oorestisime** [comment]
Hey @brivu many thanks for this. took a quick look on the PR and wondering if there is any chance this could support multiple rules at once?
We have like 15 scheduled tasks so it would be handy to avoid adding 15 jobs instead of one ( and let the orb handle looping ).

**Comment by alestuber** [comment]
I have the same case here @oorestisime , but with +100 scheduled tasks.

Other thing would be to define the cluster were the task is. How is this done today? @brivu
