### ISSUE TITLE
Error: Root Directory can not be set when using an EFS Access Point

### ISSUE THREAD

**Issue by ant-** [CircleCI-Public/aws-ecs-orb#105]
Error: Root Directory can not be set when using an EFS Access Point

## What would you like to be added
I would like to specify `efsVolumeConfiguration` with `deploy-service-update` job.

## Why is this needed

Currently, I'm having a trouble with registering a task definition. I do understand that root directory should be empty if I'm using an access point, however AWS adds it once new revision is created. 
<img width="1168" alt="Screen Shot 2020-06-01 at 16 34 32" src="https://user-images.githubusercontent.com/55976782/83414320-f470cd80-a425-11ea-912e-561cfab72d82.png">
<img width="1319" alt="Screen Shot 2020-06-01 at 16 42 35" src="https://user-images.githubusercontent.com/5741254/83414898-ea030380-a426-11ea-8273-659302657bf7.png">

**Comment by lokst** [comment]
@ant- If I understand the issue correctly, perhaps you could ensure that`efsVolumeConfiguration` is already specified in the `volumes` key in the task definition? If so, I think that `deploy-service-update` should be able to retain it when registering a new task definition based on the existing one.

**Comment by ant-** [comment]
@lokst the problem here is that `thatefsVolumeConfiguration` is in place and `deploy-service-update` tries to update it, but fails because `rootDirectory` should be empty at the moment of a task registration. However, it will be  replaced with `/` later by Amazon.

**Comment by lokst** [comment]
@ant- Thanks for clarifying the issue. I am not familiar with `efsVolumeConfiguration`, but looking at https://docs.aws.amazon.com/cli/latest/reference/ecs/register-task-definition.html, it says `Specifying / will have the same effect as omitting this parameter.` , so this sounds like unexpected behavior of the aws cli to me?

**Comment by lokst** [comment]
@ant- The new parameter made available in this PR https://github.com/CircleCI-Public/aws-ecs-orb/pull/88 could possibly help avoid the error
