### ISSUE TITLE
container-env-var-updates trims '=' characters from values

### ISSUE THREAD

**Issue by AdrianTudC** [CircleCI-Public/aws-ecs-orb#109]
### Orb version
1.2.0
### What happened
I'm passing a couple of env-vars using command `aws-ecs/update-service:` as part of a job. In `container-env-var-updates` I set a variable with a base64 value which ends in `=`. After successful deployment to ECS, In the task definition JSON view in the AWS console I see that my `=` signs at the end are trimmed.

I pass the variable this way : `container=myContainer,name="someName",value="<base64>"`
I used the quotation marks to make sure the value is not messed up because of improper formatting.

Note: Being a base64 value, the = signs are only found at the end of the value. Might be relevant.

### Expected behavior
Any `=` sign included in the `value` should be seen in the task definition JSON view in the AWS console.

**Comment by KyleTryon** [comment]
I suspect this behavior may not be caused by the orb, but by AWS. The value is fully within the quotes of the JSON object, so I don't believe the orb would be modifying this string in any way. Leaving open for now

**Comment by i-kohan** [comment]
Hello, I found this piece of code that is responsible for parsing the container_env_var_updates string. It is located in the update_container_defs.py file.
On line 37, you can see that we are splitting the value by the "=" symbol, it seems to me that this is the part that removes the "=" symbol from the value
<img width="743" alt="Снимок экрана 2022-03-25 в 14 22 05" src="https://user-images.githubusercontent.com/29607367/160102880-c0f13791-15c1-40d0-b877-a80f8d1993d3.png">
