### ISSUE TITLE
verification-timeout fails if greater than 10m

### ISSUE THREAD

**Issue by dpeterka** [CircleCI-Public/aws-ecs-orb#115]
### Orb version

1.3.0

### What happened

circleci default timeout for no standard output is 10minutes. This orb runs aws cli "wait" command and does not return output while validating.

Setting `no_output_timeout: XXm` does not work as it's not possible to include in run command as required

### Expected behavior

Task should wait longer than 10minutes with no issues.

Not sure or I would have submitted a PR. Can do a for loop in the bash if one converts *m - minutes.

**Comment by KyleTryon** [comment]
Hello @dpeterka,

I have taken a look at your request and I believe it has been addressed in version 1.4 which contains this parameter on "update service"

```
  verification-timeout:
    description: >
      The maximum amount of time to wait for a blue/green deployment to complete
      before timing out.

      Only in use when the deployment controller is the blue/green deployment
      type.
    type: string
    default: 10m
```

If this newer version does not resolve your issue, please let us know and we may follow up with further questions. Version 2.0 will be releasing in the coming weeks.
