### ISSUE TITLE
Provide a way to deregister obsolete task definitions

### ISSUE THREAD

**Issue by vladgolubev** [CircleCI-Public/aws-ecs-orb#117]
## What would you like to be added

```yaml
      - aws-ecs/update-service:
          deregister-old-task-definition: true
```

## Why is this needed

I have almost 1,000 obsolete tasks now

![image](https://user-images.githubusercontent.com/3817380/99677293-3c41ea80-2a82-11eb-8d3f-d6e2cf533dba.png)

**Comment by brivu** [comment]
Hey @vladgolubev, 

I've talked this through with our team and implementing something like this is outside of the scope of the orb. Having said that, you can deregister your outdated tasks locally on the `cli`. Here's the [link](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ecs/deregister-task-definition.html) to the documentation in case you need it.

Best, 
Brian
