### ISSUE TITLE
Support Resource Tags

### ISSUE THREAD

**Issue by dgeorges** [CircleCI-Public/aws-ecs-orb#120]
## What would you like to be added

I would like to have metadata attached to container definitions that are created by this orb in the form of aws tags. Implementation of tagging a resource can be done during its creation or after the fact.

During creation:
[register-task-definition](https://docs.aws.amazon.com/cli/latest/reference/ecs/register-task-definition.html) accepts a `--tags` argument.

After the fact:
with the [tag-resource](https://docs.aws.amazon.com/cli/latest/reference/ecs/tag-resource.html) api

Either or both would be nice to be supported by this orb.

## Why is this needed

This is helpful for release pipeline tracking, debugging and monitoring. Some tag that are useful could be:
'Approver' <- who approved the circleci pipeline
'GitSha' <- what code is part of this deploy.
'CreatedBy' <- tag that indicated resource created by "circle" for example.

I am sure there are other use cases.

**Comment by dgeorges** [comment]
HI,

I would like to take this issue on. I am not sure how approval works, so before I get started I just wanted to describe my planned change for review.

The `update-service` command will take a new parameter named `task-definition-tags` which will be a string in the format "key=<name>,value=<value>,.... If specified the task-definition will be tagged with the given tags using the `aws ecs tag-resource` api.

**Comment by brivu** [comment]
This has been merged in #127
