### ISSUE TITLE
platform-version is not used in the run-task command when using Fargate Spot

### ISSUE THREAD

**Issue by dnoji** [CircleCI-Public/aws-ecs-orb#121]
## Orb version:

2.0.0

## What happened:

`platform-version` is not used when specifying `FARGATE_SPOT` as the capacity provider in the `run-task` command. This may result in the following error if a specific platform version is required for a task definition (e.g. version 1.4.0 is required to use EFS):
```An error occurred (PlatformTaskDefinitionIncompatibilityException) when calling the RunTask operation: One or more of the requested capabilities are not supported.```

## Expected behavior:

The `--platform-version` option should be used in the AWS CLI `run-task` command when the `launch-type` is `FARGATE` or an empty string

## Additional Information:
The issue appears to be with this line:
https://github.com/CircleCI-Public/aws-ecs-orb/blob/8f17662a21ee91a7b217897666b199a7d0bb5e14/src/scripts/run-task.sh#L6

Since the `launch-type` option is required to be an empty string when specifying Fargate Spot as a capacity provider, the `--platform-version` option never gets appended to the `run-task` command

**Comment by lokst** [comment]
@dnoji Thank you for your feedback. I think a fix could be to change the default for the `platform-version` parameter from `LATEST` to `""`, and set the `--platform-version` AWS CLI argument if a non-empty string `platform-version` parameter is provided. This makes it easier to determine when `--platform-version` should be supplied.

**Comment by lokst** [comment]
This should now be resolved in `circleci/aws-ecs@2.1.0`

**Comment by dnoji** [comment]
Great, thanks!
