### ISSUE TITLE
Enable circuit breakers

### ISSUE THREAD

**Issue by mimozell** [CircleCI-Public/aws-ecs-orb#125]
## Describe Request:
Hi,

it would be nice if it would be possible to enable circuit breakers through the orb.

## Supporting Documentation Links:
Link to the cli options that include this: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ecs/update-service.html
General documentation: https://aws.amazon.com/blogs/containers/announcing-amazon-ecs-deployment-circuit-breaker/

**Comment by brivu** [comment]
This has been resolved with PR #157
