### ISSUE TITLE
Documentation for IAM Permissions and Roles required

### ISSUE THREAD

**Issue by justinhamadeunity** [CircleCI-Public/aws-ecs-orb#126]
## Describe Request:

This is more of a documentation request than a feature request.  I have searched for a while and can not find a list of the IAM Permissions or roles needed for this orb.  I will have to go through the tedious process of trial and error to try to figure it out.  I will report back here when I do.

**Comment by Renkas** [comment]
@brivu you closed this issue. Can you please reference to the documentation where the required permissions are outlined?
