### ISSUE TITLE
Latest github release is 1.4.0

### ISSUE THREAD

**Issue by jasonkarns** [CircleCI-Public/aws-ecs-orb#128]
git-tags for 2.0.0 and 2.1.0 are missing (and therefore also, the corresponding github releases are missing)

This makes it difficult to track changes between the versions.

**Comment by icco** [comment]
This is still an issue, please fix. 2.2.0 and 2.2.1 are also missing.

**Comment by jasonkarns** [comment]
This is starting to get frustrating. There's no easy way to track changes. Changelog.md in the repo is way out of date (latest entry is 2.0); latest git-tag is 1.4.0; latest github release is 1.4.0.

How are consumers expected to review changes to evaluate upgrades or debug issues?

**Comment by amc6** [comment]
For the next person to find this, it looks like version 2.2.1, the latest version at this time, is this commit: https://github.com/CircleCI-Public/aws-ecs-orb/commit/cc106a18646469884fae770a157131da490c5e19

**Comment by brivu** [comment]
Hey all, 

I'm Brian from CircleCI. Im doing a major rewrite of this orb and will cut a release for version `3.0`. 

We recently enhanced our Orb Tools which will include a change log with every new version release. 

Thanks for hanging in there and the new Orb version will be available in the upcoming weeks. 

Best, 
Brian

**Comment by brivu** [comment]
Hey all, 

Just wanted to follow up. I'm going to merge one last feature and will cut a new minor release since all issues have not been addressed yet. This release will include a change log and a new tag. 

Hope that helps!

Best, 
Brian

**Comment by brivu** [comment]
Hi All, 

I've made a new release [here](https://github.com/CircleCI-Public/aws-ecs-orb/releases/tag/v2.3.0) complete with release notes and change log. 

Hope that helps! 
Best, 
Brian
