### ISSUE TITLE
update-service command doesn't carry the ephemeralStorage information

### ISSUE THREAD

**Issue by rielcarol** [CircleCI-Public/aws-ecs-orb#132]
## What happened:
AWS has added a new parameter in the ECS tasks definitions that is called `ephemeralStorage` that is not retained when updating the service definition:
https://docs.aws.amazon.com/AmazonECS/latest/userguide/task_definition_parameters.html#task_definition_ephemeralStorage

Steps: 
* create a task definition with this value set in the JSON of the task definition:
`"ephemeralStorage": {
    "sizeInGiB": 40
}`
* use the orb to update the task definition
`- aws-ecs/update-task-definition-from-json:
      task-definition-json: ./workspace/task-definition.json
`
* use the orb to update the service
`- aws-ecs/update-service:
      family: ${TASK_FAMILY}
      cluster-name: << parameters.ecs-cluster-prefix >>-<< parameters.environment >>
      service-name: << parameters.system-code >>
      container-image-name-updates: "container=<< parameters.system-code >>,image-and-tag=${DOCKER_IMAGE}"
      verify-revision-is-deployed: true
      max-poll-attempts: 90
      poll-interval: 10
`

## Expected behavior:
The service definition should be running a task definition that has got all the settings and parameters that were defined in the task-definition registered by the command aws-ecs/update-task-definition-from-json. However when looking at the JSON of the task definition that is used to by the service the parameter 'ephemeralStorage' is not there any more.

**Comment by brivu** [comment]
Hey @rielcarol, 

Does this only happen with the `update-task-definition-from-json` command? Do you run into the same issue with the `update-task-definition` command?

Let me know!

Best, 
Brian
