### ISSUE TITLE
Why the restriction on container-env-var-updates?

### ISSUE THREAD

**Issue by stringbeans** [CircleCI-Public/aws-ecs-orb#14]
Hi again!

Just curious why when using `container-env-var-updates` it **only** updates the environment variables defined in the previous task definition. I believe that we can inject new environment variables regardless of whether they were defined previously.. (correct me if im wrong)

I'm trying to understand the rationale behind this. Would your team be open to removing the restriction?

**Comment by lokst** [comment]
Hi @stringbeans ! This was a constraint applied during the initial development of the orb to make it easy to understand what the command does, but we are open to removing it as I don't think it will cause much unexpected results for current usages.

**Comment by stringbeans** [comment]
@lokst awesome! ill take a crack at the change and submit a PR? or do you guys have the bandwidth to handle it?

**Comment by lokst** [comment]
@stringbeans It would be awesome if you could submit a PR for this! I would be happy to review it :)

**Comment by stringbeans** [comment]
@lokst sorry to bug you, but could you provide me with instructions on how to run the tests? specifically, i want to run `test_update_container_definitions.py`

im a bit unfamiliar with python so any information would help :) thanks so much

**Comment by lokst** [comment]
Closing this issue as it's been resolved in version 0.0.8 of the orb (See: https://github.com/CircleCI-Public/aws-ecs-orb/pull/15)
