### ISSUE TITLE
Upgrade aws-cli orb to auto install the CLI when setting up the AWS env

### ISSUE THREAD

**Issue by LaurentGoderre** [CircleCI-Public/aws-ecs-orb#164]
## Describe Request:

The ECR orb automatically installs the AWS CLI because it uses a new version of the CLI orb. Upgrading would make the orb more consistent.

**Comment by brivu** [comment]
Hey @LaurentGoderre, 

Just to clarify, you want this orb to reference the most up to date version of the `aws cli` orb, correct? Like [here](https://github.com/CircleCI-Public/aws-ecs-orb/blob/c46e21a2a48ddf11de99d39767a1c37ad5833965/.circleci/test-deploy.yml#L5)? https://github.com/CircleCI-Public/aws-ecs-orb/blob/c46e21a2a48ddf11de99d39767a1c37ad5833965/.circleci/test-deploy.yml#L5

Let me know if that's what you mean. 

Best, 
Brian

**Comment by LaurentGoderre** [comment]
Yes, that looks right

**Comment by brivu** [comment]
Hey @LaurentGoderre, 

I've added a bunch of fixes and features for this orb, including the latest version of the `aws cli`. I'll go ahead and cut minor a release soon and make it available for everyone. 

Best, 
Brian

**Comment by LaurentGoderre** [comment]
Awesome! Thanks!
