### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by andriyfedak** [CircleCI-Public/aws-ecs-orb#166]
## Describe Request:
PR [153](https://github.com/CircleCI-Public/aws-ecs-orb/pull/153) to enable the profile-name parameter is merged, but the currently published orb (2.2.1) seems not to include that

**Comment by brivu** [comment]
Hey @andriyfedak, 

I'm trying to merge in one last feature and will cut a minor release shortly after. Stay tuned!

Best, 
Brian

**Comment by brivu** [comment]
Hey @andriyfedak, 

Just wanted to let you know that I created a new release that you can find [here](https://github.com/CircleCI-Public/aws-ecs-orb/releases/tag/v2.3.0). 

I'm closing this issue!

Best, 
Brian
