### ISSUE TITLE
Command deploy-ecs-scheduled-task doesn't work

### ISSUE THREAD

**Issue by kassyuz** [CircleCI-Public/aws-ecs-orb#174]
## Orb version:
3.0.0

## What happened:
The command `deploy-ecs-scheduled-task` isn't work because there is bash command that doesn't exist, it is `mktmp`

Check it out at line 20 and 22 of the [command source](https://circleci.com/developer/orbs/orb/circleci/aws-ecs?version=3.0.0#commands-deploy-ecs-scheduled-task)

Also the AWS CLI command `aws events put-targets --cli-input-json "$(cat "$CLI_INPUT_FILE")"` won't work because the JSON document must has at least two attributes, Rules and Targets, it only has Targets.

## Expected behavior:

Use common bash command and have a proper JSON document.

**Comment by kassyuz** [comment]
I see the the fixes on `master` branch but any guess when will we have a release of it?

**Comment by brivu** [comment]
@kassyuz, 

I'll have a new release ready by tomorrow!

Best, 
Brian

**Comment by brivu** [comment]
Hey @kassyuz, 

I just cut a new release to include this fix: https://github.com/CircleCI-Public/aws-ecs-orb/releases/tag/v3.1.0

Hope that helps and let me know if there's anything else you need!

Best, 
Brian
