### ISSUE TITLE
Profile not set when creating deployment during a "update-service" while using the "CODE_DEPLOY" option

### ISSUE THREAD

**Issue by ryanolee** [CircleCI-Public/aws-ecs-orb#193]
## Orb version:
3.2.0

## What happened:
When using the `aws-ecs/update-service` with the `deployment-controller: "CODE_DEPLOY"` set the `profile-name` option is ignored.

## Expected behaviour:
The `--profile` should be passed to the the AWS commands used to create the deployment

**Comment by brivu** [comment]
This has been fixed in PR #202
