### ISSUE TITLE
Allow --cli-input-json in update-task-definition

### ISSUE THREAD

**Issue by BRafols** [CircleCI-Public/aws-ecs-orb#20]
My previous setup in Jenkins would always use `aws ecs register-task-definition` with the `--cli-input-json` parameter to update the previous task definition.

Would be nice if this orb allows for that option as well.

**Comment by iynere** [comment]
@BRafols hmm, it seems like all that flag does is change how you would format the parameter input to `register-task-definition`.... but our orb already parameterizes that command—instead of running `register-task-definition` at all, you just run `aws-ecs/update-service` & pass it parameters that way. so, what exactly would be the benefit here ?

**Comment by BRafols** [comment]
In my case I have a `.json` file which contains all the task definitions for a `service`. It allows me to have a greater view of how my service tasks are configured.

I would like to keep it that way, as it seems much cleaner to me. This is my example `.json` file.

```
{
  "containerDefinitions": [
    {
      "name": "logger",
      "image": "678417455204.dkr.ecr.eu-central-1.amazonaws.com/production-api-es/logger",
      "cpu": 128,
      "memoryReservation": 128
    },
    {
      "name": "nginx",
      "image": "678417455204.dkr.ecr.eu-central-1.amazonaws.com/production-api-es/nginx",
      "portMappings": [
        {
          "containerPort": 80,
          "hostPort": 80
        }
      ],
      "links": ["app:app"],
      "volumesFrom": [
        {
          "sourceContainer": "logger"
        }
      ],
      "cpu": 128,
      "memoryReservation": 256
    },
    {
      "name": "app",
      "image": "678417455204.dkr.ecr.eu-central-1.amazonaws.com/production-api-es/app",
      "portMappings": [
        {
          "containerPort": 8000,
          "hostPort": 8000
        }
      ],
      "volumesFrom": [
        {
          "sourceContainer": "logger"
        }
      ],
      "cpu": 768,
      "memoryReservation": 1024
    }
  ],
  "family": "production-api-es-web-task-definition"
}

```
I prefer to just re-register this task definition than to pass every configuration through a parameter to `update-service`.

I hope I clarified enough. Let me know if you have more questions.

**Comment by lokst** [comment]
@BRafols Thanks for explaining your use case! We'll be considering adding support for this.

**Comment by BRafols** [comment]
Thanks to you! 

Awesome job!

**Comment by egyptianbman** [comment]
Yes please! The current implementation makes the assumption that the whole task definition is static other than the image and tag. In our use case, we have one family per application and swap out the awslogs-group amount other things based on the branch -- which isn't possible with the current implementation.

**Comment by a10waveracer** [comment]
@BRafols This is now supported in v1.1.0.

@lokst This issue can be closed! Wooohoooo
