### ISSUE TITLE
Problem with tag generation with update_service command

### ISSUE THREAD

**Issue by alexgorb2016** [CircleCI-Public/aws-ecs-orb#206]
## Orb version:
v4.0.0

## What happened:
with this code orb generates full sha1 tag for docker image, but we want to see it in a shorter way.
      - aws-ecs/update_service:
          cluster: << parameters.environment >>
          family: "test-<<parameters.environment>>"
          container_image_name_updates: "container=test-<<parameters.environment>>,tag=${CIRCLE_SHA1:0:9}"

## Expected behavior:
image url should looks like 123456789 but not full sha1

## Additional Information:

It works as expected with previous version of this orb.

**Comment by marboledacci** [comment]
This is a problem with the circleci cli, which is used to manage the environment variables in the configurations, for now, you can use the workaround provided on https://github.com/CircleCI-Public/aws-ecr-orb/issues/329 until the fix is finished.
