### ISSUE TITLE
rule_name is required for non-scheduled tasks in update_task_definition

### ISSUE THREAD

**Issue by dnoji** [CircleCI-Public/aws-ecs-orb#208]
## Orb version:

4.0

## What happened:

`rule_name` is currently a required parameter in the [`update_task_definition`](https://circleci.com/developer/orbs/orb/circleci/aws-ecs#jobs-update_task_definition) job. I believe this is bug since it's only applicable to scheduled tasks and should only be required when [`deploy_scheduled_task` is true](https://github.com/CircleCI-Public/aws-ecs-orb/blob/7918a8af1188b2dd7f8b2f5eb77d5c63920c31bd/src/jobs/update_task_definition.yml#L104C14-L104C14)

## Expected behavior:

`rule_name` should not be a required parameter when `deploy_scheduled_task` is false

**Comment by marboledacci** [comment]
This is updated in this version https://circleci.com/developer/orbs/orb/circleci/aws-ecs?version=5.1.0
