### ISSUE TITLE
Cannot connect to the Docker daemon when running Build Docker Image with buildx

### ISSUE THREAD

**Issue by bdsl** [CircleCI-Public/aws-ecs-orb#209]
## What happened:

https://app.circleci.com/pipelines/github/thebiggive/donate-frontend/4811/workflows/3738181b-a8b9-4aab-820e-a66a94f23b88/jobs/13715

and other recent workflows at https://app.circleci.com/pipelines/github/thebiggive/donate-frontend?branch=develop

We haven't made any changes to our config today, but we've started seeing this error when trying to run the docker build:

```
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

Exited with code exit status 1
```

I'm not sure if this is an issue with the orb or an infrstucture issue. But https://status.circleci.com/ and https://health.aws.amazon.com/health/status are both green.

## Expected behavior:

We should see a docker image being built and pushed, as happened at https://app.circleci.com/pipelines/github/thebiggive/donate-frontend/4804/workflows/aa367876-a81c-4783-946f-48df53deebdb/jobs/13687

## Additional Information:

I tried upgrading the orb version from 8.1.3 to 8.2.1 but this doesn't seem to have had any affect. ( https://github.com/thebiggive/donate-frontend/pull/1424/files) . I also tried going to 9 but I think that has a BC break that affects us.

As we've just entered the last 24 hours of our big annual charity fundraising week, I'd be extremely grateful if anyone is able to take a look and suggest anything we can do or any fixes that can be made here so that we can get back in a position where we can deploy any changes to production quickly in case of any issues with our site.

**Comment by marboledacci** [comment]
Hi @bdsl, the aws-ecs-orb doesn't have such versions, please explain better where you face this problem, if it still happens.

**Comment by marboledacci** [comment]
I'm closing this as it doesn't seems related to this repo, please recreate in the right repo if you are still facing this issue.
