### ISSUE TITLE
Failure to retrieve previous task

### ISSUE THREAD

**Issue by sjsadowski** [CircleCI-Public/aws-ecs-orb#23]
When updating a task the previous task definition is not found.

Unfortunately the output is not very helpful, and all that I get (aside from python) in the result is:
```
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument --task-definition: expected one argument
Exited with code 2
```

**Comment by lokst** [comment]
@sjsadowski Could you link to a build where this is happening?

**Comment by sjsadowski** [comment]
Closing. Typo in config.yml

**Comment by bkovacev** [comment]
@sjsadowski Hi I'm running into this as well - could you please point me in the right direction?
