### ISSUE TITLE
Support Blue/Green Deployment

### ISSUE THREAD

**Issue by enokawa** [CircleCI-Public/aws-ecs-orb#33]
I would like to use Blue/Green Deployment.
I tryied AWS ECS Orb(`circleci/aws-ecs@0.0.11`) but not supported [Blue/Green Deployment](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/deployment-type-bluegreen.html).

This is CircleCI Output.(`Update service with registered task definition`)
```shell
#!/bin/bash -eo pipefail
SERVICE_NAME="$(echo sample)"

if [ -z "${SERVICE_NAME}" ]; then
    SERVICE_NAME="$(echo sample-app)"
fi
DEPLOYED_REVISION=$(aws ecs update-service \
    --cluster "sample-cluster" \
    --service "${SERVICE_NAME}" \
    --task-definition "${CCI_ORB_AWS_ECS_REGISTERED_TASK_DFN}" \
    --output text \
    --query service.taskDefinition)
echo "export CCI_ORB_AWS_ECS_DEPLOYED_REVISION='${DEPLOYED_REVISION}'" >> $BASH_ENV

An error occurred (InvalidParameterException) when calling the UpdateService operation: Unable to update task definition on services with a CODE_DEPLOY deployment controller. Use AWS CodeDeploy to trigger a new deployment.
Exited with code 255
```

<img width="1561" alt="Update service with registered task definition" src="https://user-images.githubusercontent.com/4405012/63958073-998bfd80-cac4-11e9-9f3f-920f33e7a9ce.png">

**Comment by lokst** [comment]
@enokawa Thank you for bringing this to our attention! We'll have to look into this.

**Comment by enokawa** [comment]
@lokst Thanks!! I'll challenge contribute to this project.
I made PR immediately #34 .

**Comment by lokst** [comment]
@enokawa Thank you so much, this is so motivating!

**Comment by lokst** [comment]
Resolved by https://github.com/CircleCI-Public/aws-ecs-orb/pull/34 🎉
