### ISSUE TITLE
Upgrade integration test infra setup to be compatible with Terraform 0.12

### ISSUE THREAD

**Issue by lokst** [CircleCI-Public/aws-ecs-orb#36]
The integration tests in `.circleci/config.yml` currently need to be pinned to being run with the `hashicorp/terraform@sha256:330bef7401e02e757e6fa2de69f398fd29fcbfafe2a3b9e8f150486fbcd7915b` docker image (which uses Terraform 0.11) 

It would be good to update the terraform files in https://github.com/CircleCI-Public/aws-ecs-orb/tree/master/tests/terraform_setup to be compatible with Terraform 0.12.

**Comment by ritvikgautam** [comment]
I was trying to take a look at this, but got the following 403:

```bash
➜ pwd
<redacted>/aws-ecs-orb/tests/terraform_setup/ec2

➜ terraform init

Initializing the backend...

Error: Failed to get existing workspaces: AccessDenied: Access Denied
	status code: 403, request id: 33C9345B7BB18D78, host id: j/jJ3GFbtOFHoPTSbqZXFdMtXmRnDMk5GGHN+JGHhudPlpAeSzZ0Gr9h71DRY7D8KCWQ1l/vOsg=

```

**Comment by lokst** [comment]
@ritvikgautam This is likely due to the s3 backend used to persist the terraform state. Could you set up the s3 backend in the `tests/terraform_setup/state_init` directory first?
