### ISSUE TITLE
Readme Not Up to Date

### ISSUE THREAD

**Issue by codingdiaz** [CircleCI-Public/aws-ecs-orb#48]
The current readme of this repo is not up to date with the latest release here: https://circleci.com/orbs/registry/orb/circleci/aws-ecs.

**Comment by sameshl** [comment]
@codingdiaz I would love to take up this issue. Could you guide me on how I could proceed in this?

**Comment by geektutor** [comment]
I would love to take this up.

**Comment by ns61817** [comment]
Let me know how I can help

**Comment by hungrybear88** [comment]
@codingdiaz  done now ?

**Comment by Sweta271097** [comment]
@codingdiaz Is this still open?

**Comment by codingdiaz** [comment]
Looks like
