### ISSUE TITLE
separate config for service name

### ISSUE THREAD

**Issue by stringbeans** [CircleCI-Public/aws-ecs-orb#5]
It looks as though this orb has a requirement for the service name and task definition name to be the same... for example, if i set `family` to `demo-web` then it will assume that both the service AND task definition is named `demo-web`

is there currently any way to separate it?

**Comment by wjbabicz** [comment]
Also having this issue. I provision my ECS resources using a Terraform module that creates a service name different from the container and task definition names.

**Comment by iynere** [comment]
@lokst can you take a look at this ? if not, i can 🙏 

otherwise, feel free to submit a PR @stringbeans @wjbabicz, don't think it should be too hard to separate those out

**Comment by stringbeans** [comment]
@iynere i dont mind submitting a PR but just to warn you i may need help with writing tests for this! :)

**Comment by stringbeans** [comment]
@wjbabicz workaround for now is to use circleci's CLI tool and run `circleci config process <config.yml>` to essentially convert your original yml with orb calls into "standard" circleci yml... 

from that point you can manually change certain lines to be whatever you need

... just out of curiousity, what terraform module are you using? i ran into this using airship's terraform modules

**Comment by iynere** [comment]
heh, don't worry about it @stringbeans 🙂 

my basic testing approach is, for any new functionality, make sure that functionality is replicated in the [integration testing workflow](https://github.com/CircleCI-Public/aws-ecs-orb/blob/41219d7a35facbcaea05eb97cefda79480ef925b/.circleci/config.yml#L393)

that said, this orb is more complex than most, so if you submit a PR with just the orb source code changes, @lokst & i can def take it the rest of the way 😀

**Comment by wjbabicz** [comment]
appreciate the workaround @stringbeans ! that did the trick.

 i'm using trussworks/ecs-service/aws for the service/initial task def + another one of their modules for the alb creation.

i'll try my best at a PR, just very green with orbs at the moment!

**Comment by rv-mobrien** [comment]
Hi guys, I was having the same issue so I ended up just publishing a new orb with this change. Check it out at https://circleci.com/orbs/registry/orb/rvla/aws-ecs

**Comment by iynere** [comment]
awesome ! @rv-mobrien we'll take a look and possibly use it to improve ours

always feel free to submit a PR to our repos rather than build your own, though (although building your own is awesome, too!)

**Comment by lokst** [comment]
Resolved by https://github.com/CircleCI-Public/aws-ecs-orb/pull/6
