### ISSUE TITLE
Support `ecs-cli compose` functionality

### ISSUE THREAD

**Issue by MorrisonCole** [CircleCI-Public/aws-ecs-orb#82]
## What would you like to be added

A new job to support [ecs-cli compose](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-compose.html) functionality.

## Why is this needed

Parity with `ecs-cli` in order to easily migrate existing scripts.

**Comment by lokst** [comment]
Thanks for the suggestion @MorrisonCole, we'll look into it!
