### ISSUE TITLE
want `update-service` without doing `update-task-definition` step

### ISSUE THREAD

**Issue by yuichiro12** [CircleCI-Public/aws-ecs-orb#85]
## What would you like to be added

Currently `update-service` always do `update-task-definition` before  updating service.
It's better to make this step optional.

## Why is this needed

For example, my use case is this:

1. run `update-task-definition`
2. run `run-task` using updated TaskDefinition to do database migration job, giving `override` option which specifies migration command.
3. run `update-service`

In this case, we don't need `update-task-definition` in `update-service` because it is already updated in previous step.

**Comment by lokst** [comment]
@yuichiro12 It should be possible to add a parameter to make `update-task-definition` optional. I'll add this enhancement to our backlog. If anyone from the community wants to make a PR for this please let us know too 🙂

**Comment by Xheno** [comment]
Hey @lokst I'll gladly look into this.

> @yuichiro12 It should be possible to add a parameter to make `update-task-definition` optional. I'll add this enhancement to our backlog. If anyone from the community wants to make a PR for this please let us know too 🙂

**Comment by lokst** [comment]
@Xheno That would be awesome, thank you!

**Comment by KyleTryon** [comment]
Appears this was closed with #88
