### ISSUE TITLE
No defaults for launch type on consumption of `run-task`

### ISSUE THREAD

**Issue by alekhrycaiko** [CircleCI-Public/aws-ecs-orb#87]
## What would you like to be added

On ecs run-task, I'd like to have a launch-type configuration that has no default values.

Currently the ECS run-task CLI doesn't require this `launch-type` parameter by default. However, the orb implementation requires this, and defaults to a `Fargate` value - which doesn't make sense for users who use `EC2` launch types. 

## Why is this needed

For users who use launch-type of EC2, the current default value creates implementation friction - as the launch-type needs to be overridden. Default values being `Fargate` here will probably cause some errors for future users that don't want their tasks run under Fargate launch type.

**Comment by alekhrycaiko** [comment]
I have a similar dilemma with the `awsvpc` setting being `true`. In my circumstances, I would prefer to not have this default to `true`; and would ideally like to set this manually if I were actually using this setting.

**Comment by lokst** [comment]
Thanks for reporting this, we'll look into revising the defaults. In the meantime, there is an example of using `run-task` for EC2 launch types on https://circleci.com/orbs/registry/orb/circleci/aws-ecs#usage-run-task-ec2
