### ISSUE TITLE
Trouble passing environmental variables to the orb

### ISSUE THREAD

**Issue by Cellane** [CircleCI-Public/aws-ecs-orb#99]
### Orb version

1.1.0, as recommended on the CircleCI Orb listing.

### What happened

I’m having issues figuring out how to pass any sort of computed variable into the orb. In my use case, I need to figure out the cluster name, service name (and perhaps other things that I’m not yet aware of) based on the branch that CircleCI is running on. For example, a commit (realistically, a PR merge) on `develop` branch means that service running on development cluster should be updated, whereas a commit on the `master` branch would indicate that production environment is to be updated.

I had a similar issue with the ECR orb when I was trying to use the jobs it defines; however, as soon as I switched to the commands it provides, the issue went away and now I can have statements like so:

```yaml
jobs:
  build-push:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - run:
          name: Determining Docker registry
          command: |
            if [[ "${CIRCLE_BRANCH}" == "develop" ]] || [[ "${CIRCLE_BRANCH}" == "circleci-integration" ]]; then
              echo "==> Deploying to development"
              echo "export REPOSITORY_NAME=<prefix>-development-app" >> $BASH_ENV
            elif [[ "${CIRCLE_BRANCH}" == "staging" ]]; then
              echo "==> Deploying to staging"
              echo "export REPOSITORY_NAME=<prefix>-staging-app" >> $BASH_ENV
            elif [[ "${CIRCLE_BRANCH}" == "master" ]]; then
              echo "==> Deploying to production"
              echo "export REPOSITORY_NAME=<prefix>-production-app" >> $BASH_ENV
            else
              echo "==> Invalid branch name"
              exit 1
            fi
      - aws-ecr/build-and-push-image:
          repo: "${REPOSITORY_NAME}"
          tag: latest
```

However, the same adjustments don’t seem to work on the ECS orb:

```yaml
  deploy:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - run:
          name: Determining ECS cluster and service
          command: |
            if [[ "${CIRCLE_BRANCH}" == "develop" ]] || [[ "${CIRCLE_BRANCH}" == "circleci-integration" ]]; then
              echo "==> Deploying to development"
              echo "export CLUSTER_NAME=<prefix>-development-cluster" >> $BASH_ENV
              echo "export SERVICE_NAME=<prefix>-development-app" >> $BASH_ENV
            elif [[ "${CIRCLE_BRANCH}" == "staging" ]]; then
              echo "==> Deploying to staging"
              echo "export CLUSTER_NAME=<prefix>-staging-cluster" >> $BASH_ENV
              echo "export SERVICE_NAME=<prefix>-staging-app" >> $BASH_ENV
            elif [[ "${CIRCLE_BRANCH}" == "master" ]]; then
              echo "==> Deploying to production"
              echo "export CLUSTER_NAME=<prefix>-production-cluster" >> $BASH_ENV
              echo "export SERVICE_NAME=<prefix>-production-app" >> $BASH_ENV
            else
              echo "==> Invalid branch name"
              exit 1
            fi
#      - aws-ecs/update-task-definition:
#          family: "${SERVICE_NAME}"
      - aws-ecs/update-service:
          cluster-name: "${CLUSTER_NAME}"
          family: "${SERVICE_NAME}"
          force-new-deployment: true
          verify-revision-is-deployed: true
```

The errors I’m getting are various. Most recently, I’m getting a `You must specify a region. You can also configure your region by running "aws configure".` error, even though `AWS_REGION` env variable is defined in the CircleCI Project Settings page (and clearly considered by the ECR Orb). Some while back, perhaps with a slightly different YAML definition (sorry, I can’t seem to find it though), I was getting the following output:

```
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]

To see help text, you can run:

  aws help
  aws <command> hel
  aws <command> <subcommand> help

Unknown options: --include, TAGS

Exited with code exit status 255
```

When I SSH into the failed job and dump environmental variables with the `env` command, I can’t see `SERVICE_NAME` nor `CLUSTER_NAME` (that is the case with both versions of the error message). I think the commands of this Orb (or at the very least, the `update-service` command) fails to load env variables defined in previous steps; but I don’t know enough about CircleCI to be sure I’m just not doing something wrong…

(One thing I noticed is that the ECR Orb defines a default executor while the ECS one doesn’t – could that be the issue?)

### Expected behavior

Consistent behaviour with the ECS Orb where environmental variables defined in previous steps are visible and considered during execution.

Thank you so much for your time reading this long report! I’ll be happy for any guidance of yours because this issue seems to be too much for me alone to tackle…

**Comment by lokst** [comment]
Hi @Cellane , sorry to hear about the difficulties you encountered. Could you try defining the `AWS_DEFAULT_REGION` environment variable for your project? The AWS CLI should be able to pick up on that. I believe `AWS_REGION` is not consistently recognized across aws cli versions, although the `circleci/aws-ecr` orb utilizes that environment variable name by default.

**Comment by Cellane** [comment]
@lokst Thank you for your answer!

I see! Actually I made a little progress since the time I wrote the original post. I decided to call both orbs after one another in the same job, and since the `aws-ecr` orb looks at the `AWS_REGION` variable and passes it to AWS CLI, it then became available to the `aws-ecs` orb as well.

Another issue I ran into was setting the `SERVICE_NAME` variable in my shell script. I think that variable name seems to be used internally by the `aws-ecs` orb (maybe?), but once I changed the `echo "export SERVICE_NAME=<prefix>-development-app" >> $BASH_ENV` lines to instead define `SERVICE` variable, things started working out perfectly 🎉

Thank you one more time – I think I have the entire pipeline mostly configured now. The only thing I’d wish for would be if the `run-task` command had an additional option, something like `stream-logs-and-wait-for-completion`. The use case would be (in my case) running a database migrator task and failing the pipeline in case the migration failed.

**Comment by lokst** [comment]
@Cellane Thank you for sharing your findings! I filed a new issue https://github.com/CircleCI-Public/aws-ecs-orb/issues/101 to capture the possible enhancement.

**Comment by amitizle** [comment]
For future reference, I bumped into the same issue and it was the AWS CLI version in the end (`1.x` which does not support the `--include` flag for the subcommand).
In my case it was a custom image with the `aws` binary installed and `aws-cli` command installed the `aws` CLI on some other path, so `aws-cli` installed the `aws` CLI correctly, but the ECR command was using the wrong version of the CLI.

Maybe it's worth checking if indeed a correct version of the CLI is installed before running any `aws` commands in this orb @lokst

**Comment by KyleTryon** [comment]
> @lokst Thank you for your answer!
> 
> I see! Actually I made a little progress since the time I wrote the original post. I decided to call both orbs after one another in the same job, and since the `aws-ecr` orb looks at the `AWS_REGION` variable and passes it to AWS CLI, it then became available to the `aws-ecs` orb as well.
> 
> Another issue I ran into was setting the `SERVICE_NAME` variable in my shell script. I think that variable name seems to be used internally by the `aws-ecs` orb (maybe?), but once I changed the `echo "export SERVICE_NAME=<prefix>-development-app" >> $BASH_ENV` lines to instead define `SERVICE` variable, things started working out perfectly 🎉
> 
> Thank you one more time – I think I have the entire pipeline mostly configured now. The only thing I’d wish for would be if the `run-task` command had an additional option, something like `stream-logs-and-wait-for-completion`. The use case would be (in my case) running a database migrator task and failing the pipeline in case the migration failed.

Confirming #118 will have all environment variables used internally prefixed to avoid this.
